### ISSUE TITLE
cloning when changing Moment

### ISSUE THREAD

**Issue by ssjssh** [fightbulc/moment.php#28]
`addXXX` or other methods in `Moment ` which change the object itself always requires `cloning` to make sure  that the original object unchanged. It would be convenient that calling  `cloning`  everytime when it is necessary.

**Comment by danhunsaker** [comment]
It sounds like what you'd like is to be able to enable an "immutable mode", where all modifications call `cloning()` automatically so you don't have to remember to.  This wouldn't be too tricky to implement - just an additional property to store which mode is in use, an additional constructor parameter to activate immutable mode on creation (defaulting to non-immutable for compatibility), possibly a method to toggle immutability after object creation (rather than directly altering the property), and a check at the beginning of each method that performs modifications to make them call `cloning()` first if the mode is enabled.

**Comment by danhunsaker** [comment]
Resolved in PR #66!
