### ISSUE TITLE
setTime function needs microseconds in PHP 7.1

### ISSUE THREAD

**Issue by nodocaengine** [fightbulc/moment.php#92]
Hi.
We are getting PHP 7.1 today, and using moment.php.
But moment.php's setTime function doesn't work now, and an error appears as below.

```
ErrorException: Declaration of Moment\Moment::setTime($hour, $minute, $second = NULL) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL)
```

It wants microseconds as argument for PHP 7.1, doesn't it?

I wish it will work.

**Comment by fightbulc** [comment]
Hey there, I had a look around but couldn't find any Interface definition with `$microseconds`.
Also first no hints on the PHP page:
- http://php.net/manual/en/datetime.settime.php
- http://php.net/manual/en/migration71.changed-functions.php

But then I've found the following:
`DateTime and DateTimeImmutable now properly incorporate microseconds when constructed from the current time, either explicitly or with a relative string (e.g. "first day of next month"). This means that naive comparisons of two newly created instances will now more likely return FALSE instead of TRUE`

A new version will be out in a moment.

**Comment by nodocaengine** [comment]
@fightbulc It works now! Thanks!
